version: '3.8'

services:
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - app-data:/app/data
    restart: unless-stopped

  client:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  app-data: 